In [7]:
import numpy as np

a1 = np.array([1,2,3,4,5])
print(type(a1))

<class 'numpy.ndarray'>


In [10]:
a2 = np.array([range(i,i+4) for i in [1,5,9,15]])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18]])

In [14]:
l3 = [2,3.4,5,6,7,8,1.3,5]
a3 = np.array(l3)
a3

array([2. , 3.4, 5. , 6. , 7. , 8. , 1.3, 5. ])

In [19]:
l4 = [3.14,4.25,5,6,7.789,45,23.45]
a4 = np.array(l4,dtype=np.int64)
a4

array([ 3,  4,  5,  6,  7, 45, 23], dtype=int64)

In [23]:
l5 = [23,45,678,54,56,231,908]
a5 = np.array([range(i,i+40,12) for i in l5],dtype=np.float32)
a5

array([[ 23.,  35.,  47.,  59.],
       [ 45.,  57.,  69.,  81.],
       [678., 690., 702., 714.],
       [ 54.,  66.,  78.,  90.],
       [ 56.,  68.,  80.,  92.],
       [231., 243., 255., 267.],
       [908., 920., 932., 944.]], dtype=float32)

In [37]:
a6 = np.zeros((5,12), dtype=np.int32)
a6

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
a7 = np.ones((5,8),dtype=np.float_)
a7

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
a8 = np.eye(5,dtype=np.float32)
a8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)

In [43]:
a9 = np.empty(3)
a9

array([ 1.41741075e-311,  0.00000000e+000, -6.47591605e-319])

In [44]:
a10 = np.arange(2,59,3)
a10

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
       53, 56])

In [45]:
a11 = np.full((3,11),4.56,dtype=np.int64)
a11

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]], dtype=int64)

In [50]:
a12 = np.linspace(0,10,11)
a12

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [54]:
rng = np.random.default_rng(seed=1701)

x1=rng.integers(10,size =(6,5))
x1

array([[9, 4, 0, 3, 8],
       [6, 3, 1, 3, 7],
       [4, 0, 2, 3, 0],
       [0, 6, 9, 4, 3],
       [5, 5, 0, 8, 3],
       [5, 2, 2, 1, 8]], dtype=int64)